In [1]:
import pandas as pd
import numpy as np

### Step 1: Import Data

The "real_estate_valuation_data_set.csv" file saves the market historical data of real estate valuation of a Chinese city. The variable information is as follows

| Variable Name | Role | Type | Description | Units | 
|:--|:--|:--|:--|:--|
|No|ID|Integer||||
|X1 transaction date|Feature|Continuous|for example, 2013.250=2013 March, <br>2013.500=2013 June, etc.||
|X2 house age|Feature|Continuous||year|
|X3 distance to the <br>nearest metro station|Feature|Continuous||meter|
|X4 number of <br>convenience stores|Feature|Integer|number of convenience stores in the<br> living circle on foot|integer|
|X5 latitude|Feature|Continuous|geographic coordinate, latitude|degree|
|X6 longitude|Feature|Continuous|geographic coordinate, longitude|degree|
|Y house price of<br> unit area|Target|Continuous|10000 Chinese Yuan per <br>square metre|10000 CNY/<br>square metre|

In [2]:
# Read the data with pandas
real_estate = pd.read_csv("real_estate_valuation_data_set.csv", index_col=0)

In [3]:
# Show the first five rows of the data
real_estate.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012.917,32.0,84.87882,10,24.98298,121.54024,2.53
2,2012.917,19.5,306.59470,9,24.98034,121.53951,2.81
3,2013.583,13.3,561.98450,5,24.98746,121.54391,3.15
4,2013.500,13.3,561.98450,5,24.98746,121.54391,3.65
5,2012.833,5.0,390.56840,5,24.97937,121.54245,2.87

In [4]:
# Get the number of instances and features
row_num = real_estate.shape[0]
col_num = real_estate.shape[1]

In [5]:
row_num, col_num

(414, 7)

In [6]:
# Get the input variables X with features from X1 to X6.
X = np.array(real_estate.iloc[:,:6].values)

In [7]:
X.shape

(414, 6)

In [8]:
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [9]:
# Get the target values y
y = np.array(real_estate.iloc[:,6].values)

In [10]:
y.shape

(414,)

In [11]:
y

array([2.53, 2.81, 3.15, 3.65, 2.87, 2.14, 2.69, 3.11, 1.25, 1.47, 2.76,
       3.87, 2.62, 1.59, 2.29, 3.37, 4.67, 2.49, 2.82, 3.18, 1.95, 3.44,
       1.64, 3.19, 2.59, 1.8 , 3.75, 2.24, 3.13, 3.81, 1.47, 1.67, 2.28,
       3.29, 3.67, 1.82, 1.53, 1.69, 3.18, 3.08, 1.06, 1.21, 2.31, 2.27,
       3.59, 2.55, 2.8 , 4.1 , 0.89, 0.88, 2.95, 1.38, 1.8 , 2.59, 3.45,
       0.91, 2.79, 3.57, 1.51, 2.83, 1.42, 4.21, 1.85, 3.67, 1.69, 2.95,
       3.38, 3.79, 2.41, 2.8 , 3.93, 2.72, 2.42, 1.33, 3.63, 1.97, 2.45,
       1.71, 1.99, 1.77, 2.69, 2.45, 3.21, 1.18, 2.91, 3.39, 1.8 , 1.22,
       3.2 , 1.69, 3.03, 2.88, 1.45, 1.07, 2.73, 3.45, 3.97, 2.31, 3.4 ,
       4.15, 2.55, 2.19, 3.63, 3.05, 2.03, 4.73, 3.14, 1.77, 2.27, 1.89,
       3.44, 2.63, 1.54, 0.51, 3.55, 3.09, 0.81, 0.87, 2.04, 3.97, 2.09,
       3.2 , 2.17, 3.03, 3.83, 3.24, 4.19, 3.67, 4.05, 2.73, 2.5 , 2.05,
       2.5 , 2.63, 2.81, 1.39, 3.12, 3.16, 2.9 , 2.83, 3.43, 1.93, 2.5 ,
       2.67, 1.89, 3.03, 3.48, 2.88, 3.01, 2.65, 3.23, 2.98, 1.93, 2.73,
       1.38, 1.04, 1.22, 2.37, 2.63, 2.49, 3.85, 2.64, 0.77, 3.7 , 3.68,
       2.04, 4.91, 2.89, 2.49, 1.57, 0.96, 3.92, 3.87, 2.34, 3.01, 2.43,
       1.28, 2.8 , 2.45, 2.84, 1.03, 3.73, 1.57, 1.25, 1.45, 1.43, 1.71,
       1.47, 2.95, 1.37, 2.82, 2.52, 2.85, 3.29, 1.95, 2.31, 2.44, 3.21,
       2.61, 2.11, 1.7 , 3.06, 2.1 , 3.07, 1.77, 1.43, 2.93, 2.28, 1.75,
       2.73, 3.48, 2.9 , 2.07, 3.87, 1.39, 3.21, 2.65, 2.72, 2.92, 2.68,
       5.22, 2.57, 3.23, 2.82, 3.07, 3.27, 0.85, 2.68, 3.11, 1.27, 2.23,
       0.98, 1.16, 2.16, 1.59, 2.62, 4.13, 2.6 , 2.71, 1.98, 1.92, 2.76,
       2.23, 3.21, 1.45, 2.72, 2.71, 1.54, 1.49, 1.  , 2.  , 0.92, 3.51,
       1.73, 3.45, 1.16, 1.77, 2.93, 4.22, 1.92, 2.05, 1.63, 3.53, 2.11,
       2.71, 2.54, 1.58, 2.74, 2.67, 1.53, 7.83, 1.77, 2.7 , 1.95, 2.73,
       3.31, 2.27, 1.85, 2.93, 2.07, 3.03, 2.99, 1.71, 1.57, 2.29, 3.69,
       3.75, 2.19, 3.4 , 2.97, 2.47, 3.63, 1.63, 2.83, 2.54, 1.45, 2.27,
       1.9 , 1.11, 3.07, 2.46, 2.38, 1.55, 2.56, 1.96, 3.67, 3.35, 1.65,
       3.53, 1.27, 1.65, 2.81, 5.2 , 2.85, 2.77, 1.82, 2.8 , 2.5 , 3.32,
       1.79, 1.24, 2.51, 2.21, 2.83, 2.09, 2.54, 4.14, 2.45, 1.57, 1.28,
       0.85, 1.04, 2.64, 2.56, 1.52, 2.43, 2.37, 2.06, 2.42, 3.36, 2.86,
       2.47, 3.57, 3.11, 2.75, 2.53, 2.05, 0.75, 3.58, 3.13, 2.82, 1.91,
       1.71, 2.09, 2.01, 4.05, 3.02, 2.99, 3.01, 1.65, 3.14, 4.22, 2.67,
       3.2 , 2.21, 1.97, 1.65, 1.39, 2.87, 1.52, 2.81, 3.45, 2.77, 3.48,
       3.3 , 1.59, 2.03, 3.79, 2.49, 4.65, 3.55, 3.15, 1.95, 2.69, 0.86,
       3.11, 3.69, 1.71, 1.82, 4.51, 2.57, 2.09, 2.35, 2.69, 1.65, 2.83,
       2.13, 2.15, 1.53, 2.49, 2.37, 1.85, 1.9 , 2.65, 2.75, 2.48, 2.7 ,
       1.49, 1.87, 1.03, 3.33, 2.71, 3.5 , 4.26])

### Step 2: Data Preprocessing

The values of features X1-X6 are in different scales. The feature in a large scale would have a huge influence on target value prediction. We shall normalize the values of different features into a uniform scale to balance the contributions of different features to target value prediction. Here we use the [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) to scale the feature values into the range of $[0,1]$. Another choice for feature normalization is [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [13]:
X

array([[0.27292576, 0.73059361, 0.00951267, 1.        , 0.61694135,
        0.71932284],
       [0.27292576, 0.44520548, 0.04380939, 0.9       , 0.5849491 ,
        0.71145137],
       [1.        , 0.30365297, 0.08331505, 0.5       , 0.67123122,
        0.75889584],
       ...,
       [0.63646288, 0.42922374, 0.05686115, 0.7       , 0.57149782,
        0.71522536],
       [0.36353712, 0.18493151, 0.0125958 , 0.5       , 0.42014057,
        0.72395946],
       [0.90938865, 0.14840183, 0.0103754 , 0.9       , 0.51211827,
        0.75016174]])

### Step 3: Train-Test Split

We randomly split the data $X$ and $y$ into training and test sets with the ratio $1:1$.

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)

### Step 4: House Price Prediction with Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression
# Train the linear regression model with the training data (X_train and y_train)
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [16]:
# Predict the target values for the test data
y_pred = reg.predict(X_test)

In [17]:
# Compare the ground-truth and predicted target values
pd.DataFrame({'y_test': y_test, 'y_pred': y_pred})

     y_test    y_pred
0      3.02  2.794503
1      0.96  0.729325
2      3.07  2.842878
3      1.04  0.714095
4      3.35  2.994068
..      ...       ...
202    2.47  2.672561
203    1.97  1.944349
204    2.24  2.905484
205    3.15  3.335583
206    1.59  2.245517

[207 rows x 2 columns]

Compute the $R^2$ score as an evaluation of the trained linear regression model. The best possible $R^2$ score is 1.0

In [18]:
reg_score = reg.score(X_test, y_test)
reg_score

0.6004683844824806

**Task 1**: Implement the [Ridge](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html) regression model (linear regression with $\ell_2$ norm regularization), compare the predicted and ground-truth target values, compute its $R^2$ score. Set the value of parameter alpha to 1.0. You can also vary the value of alpha to achieve a better performance.

In [19]:
from sklearn.linear_model import Ridge
# Train the Ridge regression model with the training data (X_train and y_train)
##: Write your code here
ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

Ridge()

In [20]:
# Predict the target values for the test data
##: Write your code here
y_pred_ridge = ridge.predict(X_test)

In [21]:
# Compare the ground-truth and predicted target values
##: Write your code here
pd.DataFrame({
    'y_test': y_test,
    'y_pred_ridge': y_pred_ridge
})

     y_test  y_pred_ridge
0      3.02      2.661983
1      0.96      0.871033
2      3.07      2.847350
3      1.04      0.854981
4      3.35      2.849535
..      ...           ...
202    2.47      2.679053
203    1.97      1.978731
204    2.24      2.872433
205    3.15      3.310660
206    1.59      2.262019

[207 rows x 2 columns]

Compute the $R^2$ score as an evaluation of the trained Ridge regression model. The best possible $R^2$ score is 1.0.

In [22]:
##: Write your code here
ridge_score = ridge.score(X_test, y_test)
ridge_score

0.6113568497057069

**Task 2**: Implement the [Lasso](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html) regression model (linear regression with $\ell_1$ norm regularization), compare the predicted and ground-truth target values, compute its $R^2$ score. Set the value of parameter alpha to 0.01. You can also vary the value of alpha to achieve a better performance.

In [23]:
from sklearn.linear_model import Lasso
# Train the Lasso regression model with the training data (X_train and y_train)
##: Write your code here
lasso = Lasso(alpha=0.01)
lasso.fit(X_train, y_train)

Lasso(alpha=0.01)

In [24]:
# Predict the target values for the test data
##: Write your code here
y_pred_lasso = lasso.predict(X_test)

In [25]:
# Compare the ground-truth and predicted target values
##: Write your code here
pd.DataFrame({
    'y_test': y_test,
    'y_pred_lasso': y_pred_lasso
})

     y_test  y_pred_lasso
0      3.02      2.757010
1      0.96      0.915037
2      3.07      2.828703
3      1.04      0.901701
4      3.35      2.905660
..      ...           ...
202    2.47      2.639978
203    1.97      2.034772
204    2.24      2.902463
205    3.15      3.197386
206    1.59      2.278318

[207 rows x 2 columns]

Compute the $R^2$ score as an evaluation of the trained Lasso regression model. The best possible $R^2$ score is 1.0.

In [26]:
##: Write your code here
lasso_score = lasso.score(X_test, y_test)
lasso_score

0.6107156271095786

**Futher Exploration (Optional)**:
+ Use features X2-X6 and X2-X4 to make predictions and evaluate the performance changes.
+ Implement the [ElasticNet](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html) regression model (linear regression with mixed $\ell_1$ and $\ell_2$ norm regularization), find its best hyperparameter configuration.
+ Transform the input variables $X$ into polynomial features with the [PolynomialFeatures](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html) interface, make predictions and evaluate the performance changes.

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#X2-X6
X_2_6 = X[:, 1:6]

X_train, X_test, y_train, y_test = train_test_split(
    X_2_6, y, test_size=0.5, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

print("R2 (X2–X6):", model.score(X_test, y_test))

#X2-X4
X_2_4 = X[:, 1:4]

X_train, X_test, y_train, y_test = train_test_split(
    X_2_4, y, test_size=0.5, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

print("R2 (X2–X4):", model.score(X_test, y_test))

R2 (X2–X6): 0.5938342227262161
R2 (X2–X4): 0.5642273899773056

In [28]:
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV

#ElasticNet
param_grid = {
    'alpha': [0.01, 0.1, 1, 10],
    'l1_ratio': [0.2, 0.5, 0.8]
}

elastic = ElasticNet(max_iter=10000)

grid = GridSearchCV(elastic, param_grid, cv=5)
grid.fit(X_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best R2:", grid.best_score_)

best_model = grid.best_estimator_

y_pred = best_model.predict(X_test)
print("Test R2:", best_model.score(X_test, y_test))

Best parameters: {'alpha': 0.01, 'l1_ratio': 0.8}
Best R2: 0.48995189801964417
Test R2: 0.5798604611143912

In [29]:
from sklearn.preprocessing import PolynomialFeatures

#PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_poly, y, test_size=0.5, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

print("Polynomial R2:", model.score(X_test, y_test))

for d in [2, 3]:
    poly = PolynomialFeatures(degree=d)
    X_poly = poly.fit_transform(X)
    
    X_train, X_test, y_train, y_test = train_test_split(
        X_poly, y, test_size=0.5, random_state=0)
    
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    print(f"Degree {d} R2:", model.score(X_test, y_test))

Polynomial R2: 0.6783368910939012
Degree 2 R2: 0.6783368910939012
Degree 3 R2: 0.0826963873443981